// <auto-generated />
using System;
using GhostSheriffsDatabaseAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PragueParking_2._0.Migrations
{
    [DbContext(typeof(VehicleContext))]
    [Migration("20220314163954_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GhostSheriffsDatabaseAccess.VehiclesDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CheckInTimeStamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("CheckInTimeStamp");

                    b.Property<string>("NumberPlate")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("NumberPlate");

                    b.Property<int>("ParkingSpot")
                        .HasColumnType("int")
                        .HasColumnName("ParkingSpot");

                    b.Property<int>("VehicleSize")
                        .HasColumnType("int")
                        .HasColumnName("VehicleSize");

                    b.Property<string>("VehicleType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VehicleType");

                    b.HasKey("Id");

                    b.HasIndex("NumberPlate")
                        .IsUnique()
                        .HasFilter("[NumberPlate] IS NOT NULL");

                    b.ToTable("Garage");
                });
#pragma warning restore 612, 618
        }
    }
}
